//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audits.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Audits.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT 
        ///	LOWES.T618_VBU_RLT.T616_VBU_NBR1 AS SFVBU, 
        ///	LOWES.T616_VBU.VBU_NME AS SFName, 
        ///	LOWES.T618_VBU_RLT.T616_VBU_NBR2 AS HOVBU, 
        ///	LOWES_T616_VBU_1.VBU_NME AS HOName, 
        ///	LOWES.T617_VBU_FNC_TYP.T617_FNC_TYP_CD, 
        ///	LOWES_T617_VBU_FNC_TYP_2.T617_FNC_TYP_CD, 
        ///	LOWES_T617_VBU_FNC_TYP_1.T617_FNC_TYP_CD, 
        ///	LOWES_T617_VBU_FNC_TYP_3.T617_FNC_TYP_CD, 
        ///	LOWES.W001_PO_DAL_HDR.T063_LCT_NBR
        ///FROM 
        ///	LOWES.W001_PO_DAL_HDR 
        ///		INNER JOIN ((((((LOWES.T618_VBU_RLT 
        ///		INNER JOIN LOWES.T616_VBU AS LOWES_T6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindSFVBU {
            get {
                return ResourceManager.GetString("FindSFVBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	LOWES.W002_PO_DAL_DTL.E058_PO_NBR 
        ///FROM 
        ///	LOWES.W002_PO_DAL_DTL 
        ///		INNER JOIN LOWES.W001_PO_DAL_HDR 
        ///			ON (LOWES.W002_PO_DAL_DTL.W002_RR_NBR = LOWES.W001_PO_DAL_HDR.W001_RR_NBR) 
        ///			AND (LOWES.W002_PO_DAL_DTL.E058_PO_NBR = LOWES.W001_PO_DAL_HDR.E058_PO_NBR)
        ///WHERE 
        ///	{0}
        ///ORDER BY LOWES.W001_PO_DAL_HDR.ARV_DT
        ///.
        /// </summary>
        internal static string GetNextAvailPO {
            get {
                return ResourceManager.GetString("GetNextAvailPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	LOWES.W001_PO_DAL_HDR.E058_PO_NBR
        ///FROM 
        ///	LOWES.W001_PO_DAL_HDR 
        ///		INNER JOIN LOWES.W002_PO_DAL_DTL 
        ///			ON (LOWES.W001_PO_DAL_HDR.T063_LCT_NBR = LOWES.W002_PO_DAL_DTL.T063_LCT_NBR) 
        ///			AND (LOWES.W001_PO_DAL_HDR.W001_RR_NBR = LOWES.W002_PO_DAL_DTL.W002_RR_NBR) 
        ///			AND (LOWES.W001_PO_DAL_HDR.E058_PO_NBR = LOWES.W002_PO_DAL_DTL.E058_PO_NBR)
        ///WHERE 
        ///	{0}
        ///ORDER BY LOWES.W001_PO_DAL_HDR.ARV_DT;.
        /// </summary>
        internal static string GetPOsFromItemList {
            get {
                return ResourceManager.GetString("GetPOsFromItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	LOWES.W002_PO_DAL_DTL.E058_PO_NBR
        ///FROM
        ///	LOWES.W002_PO_DAL_DTL
        ///WHERE
        ///	LOWES.W002_PO_DAL_DTL.T063_LCT_NBR = {1}
        ///	AND LOWES.W002_PO_DAL_DTL.ORD_QTY &gt; 0
        ///	AND LOWES.W002_PO_DAL_DTL.T024_ITM_NBR={0}
        ///	AND LOWES.W002_PO_DAL_DTL.RCV_QTY = 0
        ///	{2}.
        /// </summary>
        internal static string POItmSubQryBase {
            get {
                return ResourceManager.GetString("POItmSubQryBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr&gt;
        ///			&lt;td valign=top style=&apos;white-space:nowrap;border:none;border-right:solid #7F7F7F 1.0pt;background:white;padding:0in 5.4pt 0in 5.4pt&apos;&gt;
        ///				&lt;p class=MsoNormal align=right style=&apos;text-align:right&apos;&gt;
        ///					&lt;i&gt;
        ///						&lt;span style=&apos;font-size:13.0pt;font-family:&quot;Calibri Light&quot;,sans-serif&apos;&gt;{0}&lt;o:p&gt;&lt;/o:p&gt;&lt;/span&gt;
        ///					&lt;/i&gt;
        ///				&lt;/p&gt;
        ///			&lt;/td&gt;
        ///			&lt;td valign=top style=&apos;white-space:nowrap;;background:#F2F2F2;padding:0in 5.4pt 0in 5.4pt&apos;&gt;
        ///				&lt;p class=MsoNormal&gt;{1}&lt;o:p&gt;&lt;/o:p&gt;&lt;/p&gt;
        ///			&lt;/td&gt;
        ///			&lt;td valign=top [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PORow {
            get {
                return ResourceManager.GetString("PORow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT dbo.e537a_rcv_hdr.e058_po_nbr AS po_num, 
        ///			 subQ.RcvQty, 
        ///			 subQ.OrdQty, 
        ///			 subQ.PerComp, 
        ///			 dbo.e513_yrd_lct.e513_yrd_lct_nbr AS DoorNum, 
        ///			 dbo.e513_yrd_lct.e514_yrd_zon_nbr AS Zone,
        ///		     dbo.e537a_rcv_hdr.lnd_dm AS Landed, 
        ///			 dbo.e537a_rcv_hdr.sts_cd AS StatusCode,
        ///			 dbo.e537a_rcv_hdr.vnd_nme AS Vendor,
        ///			 dbo.e537a_rcv_hdr.cse_dm as CloseDate,
        ///			 dbo.e537a_rcv_hdr.e539_vnd_nbr_txt as VendorNum,
        ///			 dbo.e537a_rcv_hdr.t063_lct_nbr AS Facility,
        ///			 dbo.e537a_rcv_hdr.shd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string POStatus {
            get {
                return ResourceManager.GetString("POStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	LOWES.W001_PO_DAL_HDR.E058_PO_NBR,
        ///	LOWES.W001_PO_DAL_HDR.ARV_DT
        ///FROM
        ///	LOWES.W001_PO_DAL_HDR
        ///WHERE
        ///	LOWES.W001_PO_DAL_HDR.RCP_CD_TXT = &apos;N&apos;
        ///	AND LOWES.W001_PO_DAL_HDR.T063_LCT_NBR = {0}
        ///	AND LOWES.W001_PO_DAL_HDR.PO_LND_DM = &apos;1901-1-1 00:00:00&apos;
        ///	AND LOWES.W001_PO_DAL_HDR.P028_VND_NBR={1}.
        /// </summary>
        internal static string SelectPOBase {
            get {
                return ResourceManager.GetString("SelectPOBase", resourceCulture);
            }
        }
    }
}
